export { getHotelsByPrice } from "./price-range";
export {getHotelsByRoomsAndBeds} from "./room-bath";
export {getHotelsByPropertyType} from "./property";
export {getHotelsByRatings} from './rating';
export {getHotelsByCancelation} from './hotel-cancel';
export {validateEmail} from './email-regex';
export {validatePassword} from './password-regex';
export {validateNumber} from './number-regex';
export {validateName} from './name-regex';
export {findHotelInWishlist} from './find-hotel-in-wishlist';